// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: pkg/server/proto/reverb.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LookupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Prompt        string                 `protobuf:"bytes,2,opt,name=prompt,proto3" json:"prompt,omitempty"`
	ModelId       string                 `protobuf:"bytes,3,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LookupRequest) Reset() {
	*x = LookupRequest{}
	mi := &file_pkg_server_proto_reverb_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LookupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookupRequest) ProtoMessage() {}

func (x *LookupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_server_proto_reverb_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookupRequest.ProtoReflect.Descriptor instead.
func (*LookupRequest) Descriptor() ([]byte, []int) {
	return file_pkg_server_proto_reverb_proto_rawDescGZIP(), []int{0}
}

func (x *LookupRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *LookupRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *LookupRequest) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

type LookupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hit           bool                   `protobuf:"varint,1,opt,name=hit,proto3" json:"hit,omitempty"`
	Tier          string                 `protobuf:"bytes,2,opt,name=tier,proto3" json:"tier,omitempty"`
	Similarity    float32                `protobuf:"fixed32,3,opt,name=similarity,proto3" json:"similarity,omitempty"`
	Entry         *CacheEntry            `protobuf:"bytes,4,opt,name=entry,proto3" json:"entry,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LookupResponse) Reset() {
	*x = LookupResponse{}
	mi := &file_pkg_server_proto_reverb_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LookupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookupResponse) ProtoMessage() {}

func (x *LookupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_server_proto_reverb_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookupResponse.ProtoReflect.Descriptor instead.
func (*LookupResponse) Descriptor() ([]byte, []int) {
	return file_pkg_server_proto_reverb_proto_rawDescGZIP(), []int{1}
}

func (x *LookupResponse) GetHit() bool {
	if x != nil {
		return x.Hit
	}
	return false
}

func (x *LookupResponse) GetTier() string {
	if x != nil {
		return x.Tier
	}
	return ""
}

func (x *LookupResponse) GetSimilarity() float32 {
	if x != nil {
		return x.Similarity
	}
	return 0
}

func (x *LookupResponse) GetEntry() *CacheEntry {
	if x != nil {
		return x.Entry
	}
	return nil
}

type CacheEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAtUnix int64                  `protobuf:"varint,2,opt,name=created_at_unix,json=createdAtUnix,proto3" json:"created_at_unix,omitempty"`
	ExpiresAtUnix int64                  `protobuf:"varint,3,opt,name=expires_at_unix,json=expiresAtUnix,proto3" json:"expires_at_unix,omitempty"`
	Namespace     string                 `protobuf:"bytes,4,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Prompt        string                 `protobuf:"bytes,5,opt,name=prompt,proto3" json:"prompt,omitempty"`
	ModelId       string                 `protobuf:"bytes,6,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	Response      string                 `protobuf:"bytes,7,opt,name=response,proto3" json:"response,omitempty"`
	ResponseMeta  map[string]string      `protobuf:"bytes,8,rep,name=response_meta,json=responseMeta,proto3" json:"response_meta,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Sources       []*SourceRef           `protobuf:"bytes,9,rep,name=sources,proto3" json:"sources,omitempty"`
	HitCount      int64                  `protobuf:"varint,10,opt,name=hit_count,json=hitCount,proto3" json:"hit_count,omitempty"`
	Chunks        []*ResponseChunk       `protobuf:"bytes,11,rep,name=chunks,proto3" json:"chunks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CacheEntry) Reset() {
	*x = CacheEntry{}
	mi := &file_pkg_server_proto_reverb_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CacheEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheEntry) ProtoMessage() {}

func (x *CacheEntry) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_server_proto_reverb_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheEntry.ProtoReflect.Descriptor instead.
func (*CacheEntry) Descriptor() ([]byte, []int) {
	return file_pkg_server_proto_reverb_proto_rawDescGZIP(), []int{2}
}

func (x *CacheEntry) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CacheEntry) GetCreatedAtUnix() int64 {
	if x != nil {
		return x.CreatedAtUnix
	}
	return 0
}

func (x *CacheEntry) GetExpiresAtUnix() int64 {
	if x != nil {
		return x.ExpiresAtUnix
	}
	return 0
}

func (x *CacheEntry) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *CacheEntry) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *CacheEntry) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

func (x *CacheEntry) GetResponse() string {
	if x != nil {
		return x.Response
	}
	return ""
}

func (x *CacheEntry) GetResponseMeta() map[string]string {
	if x != nil {
		return x.ResponseMeta
	}
	return nil
}

func (x *CacheEntry) GetSources() []*SourceRef {
	if x != nil {
		return x.Sources
	}
	return nil
}

func (x *CacheEntry) GetHitCount() int64 {
	if x != nil {
		return x.HitCount
	}
	return 0
}

func (x *CacheEntry) GetChunks() []*ResponseChunk {
	if x != nil {
		return x.Chunks
	}
	return nil
}

// ResponseChunk is one delta in a streamed LLM response. finish_reason is
// non-empty only on the terminal chunk.
type ResponseChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Delta         string                 `protobuf:"bytes,1,opt,name=delta,proto3" json:"delta,omitempty"`
	FinishReason  string                 `protobuf:"bytes,2,opt,name=finish_reason,json=finishReason,proto3" json:"finish_reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseChunk) Reset() {
	*x = ResponseChunk{}
	mi := &file_pkg_server_proto_reverb_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseChunk) ProtoMessage() {}

func (x *ResponseChunk) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_server_proto_reverb_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseChunk.ProtoReflect.Descriptor instead.
func (*ResponseChunk) Descriptor() ([]byte, []int) {
	return file_pkg_server_proto_reverb_proto_rawDescGZIP(), []int{3}
}

func (x *ResponseChunk) GetDelta() string {
	if x != nil {
		return x.Delta
	}
	return ""
}

func (x *ResponseChunk) GetFinishReason() string {
	if x != nil {
		return x.FinishReason
	}
	return ""
}

type SourceRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SourceId      string                 `protobuf:"bytes,1,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	ContentHash   string                 `protobuf:"bytes,2,opt,name=content_hash,json=contentHash,proto3" json:"content_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SourceRef) Reset() {
	*x = SourceRef{}
	mi := &file_pkg_server_proto_reverb_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SourceRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SourceRef) ProtoMessage() {}

func (x *SourceRef) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_server_proto_reverb_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SourceRef.ProtoReflect.Descriptor instead.
func (*SourceRef) Descriptor() ([]byte, []int) {
	return file_pkg_server_proto_reverb_proto_rawDescGZIP(), []int{4}
}

func (x *SourceRef) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

func (x *SourceRef) GetContentHash() string {
	if x != nil {
		return x.ContentHash
	}
	return ""
}

type StoreRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Prompt        string                 `protobuf:"bytes,2,opt,name=prompt,proto3" json:"prompt,omitempty"`
	ModelId       string                 `protobuf:"bytes,3,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	Response      string                 `protobuf:"bytes,4,opt,name=response,proto3" json:"response,omitempty"`
	ResponseMeta  map[string]string      `protobuf:"bytes,5,rep,name=response_meta,json=responseMeta,proto3" json:"response_meta,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Sources       []*SourceRef           `protobuf:"bytes,6,rep,name=sources,proto3" json:"sources,omitempty"`
	TtlSeconds    int32                  `protobuf:"varint,7,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"`
	Chunks        []*ResponseChunk       `protobuf:"bytes,8,rep,name=chunks,proto3" json:"chunks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreRequest) Reset() {
	*x = StoreRequest{}
	mi := &file_pkg_server_proto_reverb_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreRequest) ProtoMessage() {}

func (x *StoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_server_proto_reverb_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreRequest.ProtoReflect.Descriptor instead.
func (*StoreRequest) Descriptor() ([]byte, []int) {
	return file_pkg_server_proto_reverb_proto_rawDescGZIP(), []int{5}
}

func (x *StoreRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *StoreRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *StoreRequest) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

func (x *StoreRequest) GetResponse() string {
	if x != nil {
		return x.Response
	}
	return ""
}

func (x *StoreRequest) GetResponseMeta() map[string]string {
	if x != nil {
		return x.ResponseMeta
	}
	return nil
}

func (x *StoreRequest) GetSources() []*SourceRef {
	if x != nil {
		return x.Sources
	}
	return nil
}

func (x *StoreRequest) GetTtlSeconds() int32 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

func (x *StoreRequest) GetChunks() []*ResponseChunk {
	if x != nil {
		return x.Chunks
	}
	return nil
}

type StoreResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAtUnix int64                  `protobuf:"varint,2,opt,name=created_at_unix,json=createdAtUnix,proto3" json:"created_at_unix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreResponse) Reset() {
	*x = StoreResponse{}
	mi := &file_pkg_server_proto_reverb_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreResponse) ProtoMessage() {}

func (x *StoreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_server_proto_reverb_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreResponse.ProtoReflect.Descriptor instead.
func (*StoreResponse) Descriptor() ([]byte, []int) {
	return file_pkg_server_proto_reverb_proto_rawDescGZIP(), []int{6}
}

func (x *StoreResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *StoreResponse) GetCreatedAtUnix() int64 {
	if x != nil {
		return x.CreatedAtUnix
	}
	return 0
}

type InvalidateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SourceId      string                 `protobuf:"bytes,1,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvalidateRequest) Reset() {
	*x = InvalidateRequest{}
	mi := &file_pkg_server_proto_reverb_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvalidateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvalidateRequest) ProtoMessage() {}

func (x *InvalidateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_server_proto_reverb_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvalidateRequest.ProtoReflect.Descriptor instead.
func (*InvalidateRequest) Descriptor() ([]byte, []int) {
	return file_pkg_server_proto_reverb_proto_rawDescGZIP(), []int{7}
}

func (x *InvalidateRequest) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

type InvalidateResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	InvalidatedCount int32                  `protobuf:"varint,1,opt,name=invalidated_count,json=invalidatedCount,proto3" json:"invalidated_count,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *InvalidateResponse) Reset() {
	*x = InvalidateResponse{}
	mi := &file_pkg_server_proto_reverb_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvalidateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvalidateResponse) ProtoMessage() {}

func (x *InvalidateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_server_proto_reverb_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvalidateResponse.ProtoReflect.Descriptor instead.
func (*InvalidateResponse) Descriptor() ([]byte, []int) {
	return file_pkg_server_proto_reverb_proto_rawDescGZIP(), []int{8}
}

func (x *InvalidateResponse) GetInvalidatedCount() int32 {
	if x != nil {
		return x.InvalidatedCount
	}
	return 0
}

type DeleteEntryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteEntryRequest) Reset() {
	*x = DeleteEntryRequest{}
	mi := &file_pkg_server_proto_reverb_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteEntryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteEntryRequest) ProtoMessage() {}

func (x *DeleteEntryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_server_proto_reverb_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteEntryRequest.ProtoReflect.Descriptor instead.
func (*DeleteEntryRequest) Descriptor() ([]byte, []int) {
	return file_pkg_server_proto_reverb_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteEntryRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteEntryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteEntryResponse) Reset() {
	*x = DeleteEntryResponse{}
	mi := &file_pkg_server_proto_reverb_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteEntryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteEntryResponse) ProtoMessage() {}

func (x *DeleteEntryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_server_proto_reverb_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteEntryResponse.ProtoReflect.Descriptor instead.
func (*DeleteEntryResponse) Descriptor() ([]byte, []int) {
	return file_pkg_server_proto_reverb_proto_rawDescGZIP(), []int{10}
}

type GetStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatsRequest) Reset() {
	*x = GetStatsRequest{}
	mi := &file_pkg_server_proto_reverb_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatsRequest) ProtoMessage() {}

func (x *GetStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_server_proto_reverb_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatsRequest.ProtoReflect.Descriptor instead.
func (*GetStatsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_server_proto_reverb_proto_rawDescGZIP(), []int{11}
}

type GetStatsResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	TotalEntries       int64                  `protobuf:"varint,1,opt,name=total_entries,json=totalEntries,proto3" json:"total_entries,omitempty"`
	Namespaces         []string               `protobuf:"bytes,2,rep,name=namespaces,proto3" json:"namespaces,omitempty"`
	ExactHitsTotal     int64                  `protobuf:"varint,3,opt,name=exact_hits_total,json=exactHitsTotal,proto3" json:"exact_hits_total,omitempty"`
	SemanticHitsTotal  int64                  `protobuf:"varint,4,opt,name=semantic_hits_total,json=semanticHitsTotal,proto3" json:"semantic_hits_total,omitempty"`
	MissesTotal        int64                  `protobuf:"varint,5,opt,name=misses_total,json=missesTotal,proto3" json:"misses_total,omitempty"`
	InvalidationsTotal int64                  `protobuf:"varint,6,opt,name=invalidations_total,json=invalidationsTotal,proto3" json:"invalidations_total,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GetStatsResponse) Reset() {
	*x = GetStatsResponse{}
	mi := &file_pkg_server_proto_reverb_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatsResponse) ProtoMessage() {}

func (x *GetStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_server_proto_reverb_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatsResponse.ProtoReflect.Descriptor instead.
func (*GetStatsResponse) Descriptor() ([]byte, []int) {
	return file_pkg_server_proto_reverb_proto_rawDescGZIP(), []int{12}
}

func (x *GetStatsResponse) GetTotalEntries() int64 {
	if x != nil {
		return x.TotalEntries
	}
	return 0
}

func (x *GetStatsResponse) GetNamespaces() []string {
	if x != nil {
		return x.Namespaces
	}
	return nil
}

func (x *GetStatsResponse) GetExactHitsTotal() int64 {
	if x != nil {
		return x.ExactHitsTotal
	}
	return 0
}

func (x *GetStatsResponse) GetSemanticHitsTotal() int64 {
	if x != nil {
		return x.SemanticHitsTotal
	}
	return 0
}

func (x *GetStatsResponse) GetMissesTotal() int64 {
	if x != nil {
		return x.MissesTotal
	}
	return 0
}

func (x *GetStatsResponse) GetInvalidationsTotal() int64 {
	if x != nil {
		return x.InvalidationsTotal
	}
	return 0
}

var File_pkg_server_proto_reverb_proto protoreflect.FileDescriptor

const file_pkg_server_proto_reverb_proto_rawDesc = "" +
	"\n" +
	"\x1dpkg/server/proto/reverb.proto\x12\treverb.v1\"`\n" +
	"\rLookupRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x16\n" +
	"\x06prompt\x18\x02 \x01(\tR\x06prompt\x12\x19\n" +
	"\bmodel_id\x18\x03 \x01(\tR\amodelId\"\x83\x01\n" +
	"\x0eLookupResponse\x12\x10\n" +
	"\x03hit\x18\x01 \x01(\bR\x03hit\x12\x12\n" +
	"\x04tier\x18\x02 \x01(\tR\x04tier\x12\x1e\n" +
	"\n" +
	"similarity\x18\x03 \x01(\x02R\n" +
	"similarity\x12+\n" +
	"\x05entry\x18\x04 \x01(\v2\x15.reverb.v1.CacheEntryR\x05entry\"\xe7\x03\n" +
	"\n" +
	"CacheEntry\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12&\n" +
	"\x0fcreated_at_unix\x18\x02 \x01(\x03R\rcreatedAtUnix\x12&\n" +
	"\x0fexpires_at_unix\x18\x03 \x01(\x03R\rexpiresAtUnix\x12\x1c\n" +
	"\tnamespace\x18\x04 \x01(\tR\tnamespace\x12\x16\n" +
	"\x06prompt\x18\x05 \x01(\tR\x06prompt\x12\x19\n" +
	"\bmodel_id\x18\x06 \x01(\tR\amodelId\x12\x1a\n" +
	"\bresponse\x18\a \x01(\tR\bresponse\x12L\n" +
	"\rresponse_meta\x18\b \x03(\v2'.reverb.v1.CacheEntry.ResponseMetaEntryR\fresponseMeta\x12.\n" +
	"\asources\x18\t \x03(\v2\x14.reverb.v1.SourceRefR\asources\x12\x1b\n" +
	"\thit_count\x18\n" +
	" \x01(\x03R\bhitCount\x120\n" +
	"\x06chunks\x18\v \x03(\v2\x18.reverb.v1.ResponseChunkR\x06chunks\x1a?\n" +
	"\x11ResponseMetaEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"J\n" +
	"\rResponseChunk\x12\x14\n" +
	"\x05delta\x18\x01 \x01(\tR\x05delta\x12#\n" +
	"\rfinish_reason\x18\x02 \x01(\tR\ffinishReason\"K\n" +
	"\tSourceRef\x12\x1b\n" +
	"\tsource_id\x18\x01 \x01(\tR\bsourceId\x12!\n" +
	"\fcontent_hash\x18\x02 \x01(\tR\vcontentHash\"\x8f\x03\n" +
	"\fStoreRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x16\n" +
	"\x06prompt\x18\x02 \x01(\tR\x06prompt\x12\x19\n" +
	"\bmodel_id\x18\x03 \x01(\tR\amodelId\x12\x1a\n" +
	"\bresponse\x18\x04 \x01(\tR\bresponse\x12N\n" +
	"\rresponse_meta\x18\x05 \x03(\v2).reverb.v1.StoreRequest.ResponseMetaEntryR\fresponseMeta\x12.\n" +
	"\asources\x18\x06 \x03(\v2\x14.reverb.v1.SourceRefR\asources\x12\x1f\n" +
	"\vttl_seconds\x18\a \x01(\x05R\n" +
	"ttlSeconds\x120\n" +
	"\x06chunks\x18\b \x03(\v2\x18.reverb.v1.ResponseChunkR\x06chunks\x1a?\n" +
	"\x11ResponseMetaEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"G\n" +
	"\rStoreResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12&\n" +
	"\x0fcreated_at_unix\x18\x02 \x01(\x03R\rcreatedAtUnix\"0\n" +
	"\x11InvalidateRequest\x12\x1b\n" +
	"\tsource_id\x18\x01 \x01(\tR\bsourceId\"A\n" +
	"\x12InvalidateResponse\x12+\n" +
	"\x11invalidated_count\x18\x01 \x01(\x05R\x10invalidatedCount\"$\n" +
	"\x12DeleteEntryRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x15\n" +
	"\x13DeleteEntryResponse\"\x11\n" +
	"\x0fGetStatsRequest\"\x85\x02\n" +
	"\x10GetStatsResponse\x12#\n" +
	"\rtotal_entries\x18\x01 \x01(\x03R\ftotalEntries\x12\x1e\n" +
	"\n" +
	"namespaces\x18\x02 \x03(\tR\n" +
	"namespaces\x12(\n" +
	"\x10exact_hits_total\x18\x03 \x01(\x03R\x0eexactHitsTotal\x12.\n" +
	"\x13semantic_hits_total\x18\x04 \x01(\x03R\x11semanticHitsTotal\x12!\n" +
	"\fmisses_total\x18\x05 \x01(\x03R\vmissesTotal\x12/\n" +
	"\x13invalidations_total\x18\x06 \x01(\x03R\x12invalidationsTotal2\xae\x03\n" +
	"\rReverbService\x12=\n" +
	"\x06Lookup\x12\x18.reverb.v1.LookupRequest\x1a\x19.reverb.v1.LookupResponse\x12D\n" +
	"\fLookupStream\x12\x18.reverb.v1.LookupRequest\x1a\x18.reverb.v1.ResponseChunk0\x01\x12:\n" +
	"\x05Store\x12\x17.reverb.v1.StoreRequest\x1a\x18.reverb.v1.StoreResponse\x12I\n" +
	"\n" +
	"Invalidate\x12\x1c.reverb.v1.InvalidateRequest\x1a\x1d.reverb.v1.InvalidateResponse\x12L\n" +
	"\vDeleteEntry\x12\x1d.reverb.v1.DeleteEntryRequest\x1a\x1e.reverb.v1.DeleteEntryResponse\x12C\n" +
	"\bGetStats\x12\x1a.reverb.v1.GetStatsRequest\x1a\x1b.reverb.v1.GetStatsResponseB+Z)github.com/nobelk/reverb/pkg/server/protob\x06proto3"

var (
	file_pkg_server_proto_reverb_proto_rawDescOnce sync.Once
	file_pkg_server_proto_reverb_proto_rawDescData []byte
)

func file_pkg_server_proto_reverb_proto_rawDescGZIP() []byte {
	file_pkg_server_proto_reverb_proto_rawDescOnce.Do(func() {
		file_pkg_server_proto_reverb_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_server_proto_reverb_proto_rawDesc), len(file_pkg_server_proto_reverb_proto_rawDesc)))
	})
	return file_pkg_server_proto_reverb_proto_rawDescData
}

var file_pkg_server_proto_reverb_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_pkg_server_proto_reverb_proto_goTypes = []any{
	(*LookupRequest)(nil),       // 0: reverb.v1.LookupRequest
	(*LookupResponse)(nil),      // 1: reverb.v1.LookupResponse
	(*CacheEntry)(nil),          // 2: reverb.v1.CacheEntry
	(*ResponseChunk)(nil),       // 3: reverb.v1.ResponseChunk
	(*SourceRef)(nil),           // 4: reverb.v1.SourceRef
	(*StoreRequest)(nil),        // 5: reverb.v1.StoreRequest
	(*StoreResponse)(nil),       // 6: reverb.v1.StoreResponse
	(*InvalidateRequest)(nil),   // 7: reverb.v1.InvalidateRequest
	(*InvalidateResponse)(nil),  // 8: reverb.v1.InvalidateResponse
	(*DeleteEntryRequest)(nil),  // 9: reverb.v1.DeleteEntryRequest
	(*DeleteEntryResponse)(nil), // 10: reverb.v1.DeleteEntryResponse
	(*GetStatsRequest)(nil),     // 11: reverb.v1.GetStatsRequest
	(*GetStatsResponse)(nil),    // 12: reverb.v1.GetStatsResponse
	nil,                         // 13: reverb.v1.CacheEntry.ResponseMetaEntry
	nil,                         // 14: reverb.v1.StoreRequest.ResponseMetaEntry
}
var file_pkg_server_proto_reverb_proto_depIdxs = []int32{
	2,  // 0: reverb.v1.LookupResponse.entry:type_name -> reverb.v1.CacheEntry
	13, // 1: reverb.v1.CacheEntry.response_meta:type_name -> reverb.v1.CacheEntry.ResponseMetaEntry
	4,  // 2: reverb.v1.CacheEntry.sources:type_name -> reverb.v1.SourceRef
	3,  // 3: reverb.v1.CacheEntry.chunks:type_name -> reverb.v1.ResponseChunk
	14, // 4: reverb.v1.StoreRequest.response_meta:type_name -> reverb.v1.StoreRequest.ResponseMetaEntry
	4,  // 5: reverb.v1.StoreRequest.sources:type_name -> reverb.v1.SourceRef
	3,  // 6: reverb.v1.StoreRequest.chunks:type_name -> reverb.v1.ResponseChunk
	0,  // 7: reverb.v1.ReverbService.Lookup:input_type -> reverb.v1.LookupRequest
	0,  // 8: reverb.v1.ReverbService.LookupStream:input_type -> reverb.v1.LookupRequest
	5,  // 9: reverb.v1.ReverbService.Store:input_type -> reverb.v1.StoreRequest
	7,  // 10: reverb.v1.ReverbService.Invalidate:input_type -> reverb.v1.InvalidateRequest
	9,  // 11: reverb.v1.ReverbService.DeleteEntry:input_type -> reverb.v1.DeleteEntryRequest
	11, // 12: reverb.v1.ReverbService.GetStats:input_type -> reverb.v1.GetStatsRequest
	1,  // 13: reverb.v1.ReverbService.Lookup:output_type -> reverb.v1.LookupResponse
	3,  // 14: reverb.v1.ReverbService.LookupStream:output_type -> reverb.v1.ResponseChunk
	6,  // 15: reverb.v1.ReverbService.Store:output_type -> reverb.v1.StoreResponse
	8,  // 16: reverb.v1.ReverbService.Invalidate:output_type -> reverb.v1.InvalidateResponse
	10, // 17: reverb.v1.ReverbService.DeleteEntry:output_type -> reverb.v1.DeleteEntryResponse
	12, // 18: reverb.v1.ReverbService.GetStats:output_type -> reverb.v1.GetStatsResponse
	13, // [13:19] is the sub-list for method output_type
	7,  // [7:13] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_pkg_server_proto_reverb_proto_init() }
func file_pkg_server_proto_reverb_proto_init() {
	if File_pkg_server_proto_reverb_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_server_proto_reverb_proto_rawDesc), len(file_pkg_server_proto_reverb_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_server_proto_reverb_proto_goTypes,
		DependencyIndexes: file_pkg_server_proto_reverb_proto_depIdxs,
		MessageInfos:      file_pkg_server_proto_reverb_proto_msgTypes,
	}.Build()
	File_pkg_server_proto_reverb_proto = out.File
	file_pkg_server_proto_reverb_proto_goTypes = nil
	file_pkg_server_proto_reverb_proto_depIdxs = nil
}
