// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: pkg/server/proto/reverb.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ReverbService_Lookup_FullMethodName       = "/reverb.v1.ReverbService/Lookup"
	ReverbService_LookupStream_FullMethodName = "/reverb.v1.ReverbService/LookupStream"
	ReverbService_Store_FullMethodName        = "/reverb.v1.ReverbService/Store"
	ReverbService_Invalidate_FullMethodName   = "/reverb.v1.ReverbService/Invalidate"
	ReverbService_DeleteEntry_FullMethodName  = "/reverb.v1.ReverbService/DeleteEntry"
	ReverbService_GetStats_FullMethodName     = "/reverb.v1.ReverbService/GetStats"
)

// ReverbServiceClient is the client API for ReverbService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ReverbService provides semantic response caching with knowledge-aware invalidation.
type ReverbServiceClient interface {
	// Lookup checks the cache for a matching response.
	Lookup(ctx context.Context, in *LookupRequest, opts ...grpc.CallOption) (*LookupResponse, error)
	// LookupStream replays a cached response as a stream of chunks. On a miss,
	// the server closes the stream with codes.NotFound; on a hit, it emits one
	// ResponseChunk per stored chunk and closes cleanly. Entries stored without
	// chunks are emitted as a single chunk carrying the full response text and
	// finish_reason="stop".
	LookupStream(ctx context.Context, in *LookupRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ResponseChunk], error)
	// Store writes a new cache entry.
	Store(ctx context.Context, in *StoreRequest, opts ...grpc.CallOption) (*StoreResponse, error)
	// Invalidate invalidates all cache entries that depend on the given source.
	Invalidate(ctx context.Context, in *InvalidateRequest, opts ...grpc.CallOption) (*InvalidateResponse, error)
	// DeleteEntry removes a single cache entry by ID.
	DeleteEntry(ctx context.Context, in *DeleteEntryRequest, opts ...grpc.CallOption) (*DeleteEntryResponse, error)
	// GetStats returns cache statistics.
	GetStats(ctx context.Context, in *GetStatsRequest, opts ...grpc.CallOption) (*GetStatsResponse, error)
}

type reverbServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewReverbServiceClient(cc grpc.ClientConnInterface) ReverbServiceClient {
	return &reverbServiceClient{cc}
}

func (c *reverbServiceClient) Lookup(ctx context.Context, in *LookupRequest, opts ...grpc.CallOption) (*LookupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LookupResponse)
	err := c.cc.Invoke(ctx, ReverbService_Lookup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reverbServiceClient) LookupStream(ctx context.Context, in *LookupRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ResponseChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ReverbService_ServiceDesc.Streams[0], ReverbService_LookupStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[LookupRequest, ResponseChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ReverbService_LookupStreamClient = grpc.ServerStreamingClient[ResponseChunk]

func (c *reverbServiceClient) Store(ctx context.Context, in *StoreRequest, opts ...grpc.CallOption) (*StoreResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StoreResponse)
	err := c.cc.Invoke(ctx, ReverbService_Store_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reverbServiceClient) Invalidate(ctx context.Context, in *InvalidateRequest, opts ...grpc.CallOption) (*InvalidateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InvalidateResponse)
	err := c.cc.Invoke(ctx, ReverbService_Invalidate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reverbServiceClient) DeleteEntry(ctx context.Context, in *DeleteEntryRequest, opts ...grpc.CallOption) (*DeleteEntryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteEntryResponse)
	err := c.cc.Invoke(ctx, ReverbService_DeleteEntry_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reverbServiceClient) GetStats(ctx context.Context, in *GetStatsRequest, opts ...grpc.CallOption) (*GetStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStatsResponse)
	err := c.cc.Invoke(ctx, ReverbService_GetStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ReverbServiceServer is the server API for ReverbService service.
// All implementations must embed UnimplementedReverbServiceServer
// for forward compatibility.
//
// ReverbService provides semantic response caching with knowledge-aware invalidation.
type ReverbServiceServer interface {
	// Lookup checks the cache for a matching response.
	Lookup(context.Context, *LookupRequest) (*LookupResponse, error)
	// LookupStream replays a cached response as a stream of chunks. On a miss,
	// the server closes the stream with codes.NotFound; on a hit, it emits one
	// ResponseChunk per stored chunk and closes cleanly. Entries stored without
	// chunks are emitted as a single chunk carrying the full response text and
	// finish_reason="stop".
	LookupStream(*LookupRequest, grpc.ServerStreamingServer[ResponseChunk]) error
	// Store writes a new cache entry.
	Store(context.Context, *StoreRequest) (*StoreResponse, error)
	// Invalidate invalidates all cache entries that depend on the given source.
	Invalidate(context.Context, *InvalidateRequest) (*InvalidateResponse, error)
	// DeleteEntry removes a single cache entry by ID.
	DeleteEntry(context.Context, *DeleteEntryRequest) (*DeleteEntryResponse, error)
	// GetStats returns cache statistics.
	GetStats(context.Context, *GetStatsRequest) (*GetStatsResponse, error)
	mustEmbedUnimplementedReverbServiceServer()
}

// UnimplementedReverbServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedReverbServiceServer struct{}

func (UnimplementedReverbServiceServer) Lookup(context.Context, *LookupRequest) (*LookupResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Lookup not implemented")
}
func (UnimplementedReverbServiceServer) LookupStream(*LookupRequest, grpc.ServerStreamingServer[ResponseChunk]) error {
	return status.Error(codes.Unimplemented, "method LookupStream not implemented")
}
func (UnimplementedReverbServiceServer) Store(context.Context, *StoreRequest) (*StoreResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Store not implemented")
}
func (UnimplementedReverbServiceServer) Invalidate(context.Context, *InvalidateRequest) (*InvalidateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Invalidate not implemented")
}
func (UnimplementedReverbServiceServer) DeleteEntry(context.Context, *DeleteEntryRequest) (*DeleteEntryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteEntry not implemented")
}
func (UnimplementedReverbServiceServer) GetStats(context.Context, *GetStatsRequest) (*GetStatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStats not implemented")
}
func (UnimplementedReverbServiceServer) mustEmbedUnimplementedReverbServiceServer() {}
func (UnimplementedReverbServiceServer) testEmbeddedByValue()                       {}

// UnsafeReverbServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ReverbServiceServer will
// result in compilation errors.
type UnsafeReverbServiceServer interface {
	mustEmbedUnimplementedReverbServiceServer()
}

func RegisterReverbServiceServer(s grpc.ServiceRegistrar, srv ReverbServiceServer) {
	// If the following call panics, it indicates UnimplementedReverbServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ReverbService_ServiceDesc, srv)
}

func _ReverbService_Lookup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LookupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReverbServiceServer).Lookup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReverbService_Lookup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReverbServiceServer).Lookup(ctx, req.(*LookupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReverbService_LookupStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(LookupRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ReverbServiceServer).LookupStream(m, &grpc.GenericServerStream[LookupRequest, ResponseChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ReverbService_LookupStreamServer = grpc.ServerStreamingServer[ResponseChunk]

func _ReverbService_Store_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReverbServiceServer).Store(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReverbService_Store_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReverbServiceServer).Store(ctx, req.(*StoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReverbService_Invalidate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InvalidateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReverbServiceServer).Invalidate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReverbService_Invalidate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReverbServiceServer).Invalidate(ctx, req.(*InvalidateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReverbService_DeleteEntry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteEntryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReverbServiceServer).DeleteEntry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReverbService_DeleteEntry_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReverbServiceServer).DeleteEntry(ctx, req.(*DeleteEntryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReverbService_GetStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReverbServiceServer).GetStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReverbService_GetStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReverbServiceServer).GetStats(ctx, req.(*GetStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ReverbService_ServiceDesc is the grpc.ServiceDesc for ReverbService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ReverbService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "reverb.v1.ReverbService",
	HandlerType: (*ReverbServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Lookup",
			Handler:    _ReverbService_Lookup_Handler,
		},
		{
			MethodName: "Store",
			Handler:    _ReverbService_Store_Handler,
		},
		{
			MethodName: "Invalidate",
			Handler:    _ReverbService_Invalidate_Handler,
		},
		{
			MethodName: "DeleteEntry",
			Handler:    _ReverbService_DeleteEntry_Handler,
		},
		{
			MethodName: "GetStats",
			Handler:    _ReverbService_GetStats_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "LookupStream",
			Handler:       _ReverbService_LookupStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "pkg/server/proto/reverb.proto",
}
