"""Wire-level dataclasses mirroring ``openapi/v1.yaml`` schemas.

These are hand-written for the 0.1 release. A future minor will swap them
for code generated by openapi-generator-cli; the public field names and
JSON keys here match the spec exactly so that swap stays compatible.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any


@dataclass(frozen=True)
class SourceRef:
    """One element of a cache entry's lineage."""

    source_id: str
    content_hash: str

    def to_wire(self) -> dict[str, str]:
        return {"source_id": self.source_id, "content_hash": self.content_hash}

    @classmethod
    def from_wire(cls, data: dict[str, Any]) -> SourceRef:
        return cls(source_id=data["source_id"], content_hash=data["content_hash"])


@dataclass(frozen=True)
class CacheEntry:
    id: str
    created_at: str
    namespace: str
    prompt: str
    model_id: str
    response: str
    hit_count: int
    expires_at: str | None = None
    response_meta: dict[str, str] = field(default_factory=dict)
    sources: list[SourceRef] = field(default_factory=list)

    @classmethod
    def from_wire(cls, data: dict[str, Any]) -> CacheEntry:
        return cls(
            id=data["id"],
            created_at=data["created_at"],
            namespace=data["namespace"],
            prompt=data["prompt"],
            model_id=data["model_id"],
            response=data["response"],
            hit_count=int(data["hit_count"]),
            expires_at=data.get("expires_at"),
            response_meta=dict(data.get("response_meta") or {}),
            sources=[SourceRef.from_wire(s) for s in (data.get("sources") or [])],
        )


@dataclass(frozen=True)
class LookupResponse:
    """Result of ``POST /v1/lookup``.

    ``hit`` is always populated; ``tier``, ``similarity``, and ``entry`` are
    populated only when ``hit=True``.
    """

    hit: bool
    tier: str | None = None
    similarity: float | None = None
    entry: CacheEntry | None = None

    @classmethod
    def from_wire(cls, data: dict[str, Any]) -> LookupResponse:
        entry_data = data.get("entry")
        return cls(
            hit=bool(data["hit"]),
            tier=data.get("tier") or None,
            similarity=float(data["similarity"]) if data.get("similarity") is not None else None,
            entry=CacheEntry.from_wire(entry_data) if entry_data else None,
        )


@dataclass(frozen=True)
class StoreResponse:
    id: str
    created_at: str

    @classmethod
    def from_wire(cls, data: dict[str, Any]) -> StoreResponse:
        return cls(id=data["id"], created_at=data["created_at"])


@dataclass(frozen=True)
class StatsResponse:
    total_entries: int
    namespaces: list[str]
    exact_hits_total: int
    semantic_hits_total: int
    misses_total: int
    invalidations_total: int
    hit_rate: float

    @classmethod
    def from_wire(cls, data: dict[str, Any]) -> StatsResponse:
        return cls(
            total_entries=int(data["total_entries"]),
            namespaces=list(data.get("namespaces") or []),
            exact_hits_total=int(data["exact_hits_total"]),
            semantic_hits_total=int(data["semantic_hits_total"]),
            misses_total=int(data["misses_total"]),
            invalidations_total=int(data["invalidations_total"]),
            hit_rate=float(data["hit_rate"]),
        )
