// Wire-level types mirroring openapi/v1.yaml.
//
// These are hand-written for the 0.1 release. A future minor will swap them
// for code generated by openapi-generator-cli; the field names here match
// the spec's JSON keys exactly so the swap stays compatible.

export interface SourceRef {
  source_id: string;
  /** SHA-256 of the source content, hex-encoded (lowercase, no `0x`). 64 chars. */
  content_hash: string;
}

export interface ResponseChunk {
  delta: string;
  /** Set on the terminal chunk only. Mirrors OpenAI ("stop", "length", ...). */
  finish_reason?: string;
}

export interface CacheEntry {
  id: string;
  created_at: string;
  expires_at?: string;
  namespace: string;
  prompt: string;
  model_id: string;
  response: string;
  chunks?: ResponseChunk[];
  response_meta?: Record<string, string>;
  sources?: SourceRef[];
  hit_count: number;
}

export interface LookupRequest {
  namespace: string;
  prompt: string;
  model_id?: string;
}

export interface LookupResponse {
  hit: boolean;
  tier?: "exact" | "semantic";
  similarity?: number;
  entry?: CacheEntry;
}

export interface StoreRequest {
  namespace: string;
  prompt: string;
  model_id?: string;
  /** Either `response` or `chunks` is required. */
  response?: string;
  /** Either `response` or `chunks` is required. */
  chunks?: ResponseChunk[];
  response_meta?: Record<string, string>;
  sources?: SourceRef[];
  ttl_seconds?: number;
}

export interface StoreResponse {
  id: string;
  created_at: string;
}

export interface InvalidateRequest {
  source_id: string;
}

export interface InvalidateResponse {
  invalidated_count: number;
}

export interface StatsResponse {
  total_entries: number;
  namespaces: string[];
  exact_hits_total: number;
  semantic_hits_total: number;
  misses_total: number;
  invalidations_total: number;
  hit_rate: number;
}

export interface HealthResponse {
  status: "ok";
}

export interface ErrorPayload {
  error: string;
}
